# Generated by Django 3.2.8 on 2021-10-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('id_identification_type', models.IntegerField(verbose_name='')),
                ('number_id', models.CharField(max_length=50)),
                ('id_city', models.IntegerField(verbose_name='')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('status', models.BooleanField(verbose_name='')),
                ('created_at', models.DateTimeField(verbose_name='')),
                ('updated_at', models.DateTimeField(verbose_name='')),
                ('deleted_at', models.DateTimeField(verbose_name='')),
            ],
        ),
    ]
