# Generated by Django 3.2.8 on 2021-10-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='')),
                ('name', models.CharField(max_length=150, verbose_name='')),
                ('abrev', models.CharField(max_length=4, verbose_name='')),
                ('id_country', models.IntegerField(verbose_name='')),
                ('status', models.BooleanField(verbose_name='')),
                ('created_at', models.DateTimeField(verbose_name='')),
                ('updated_at', models.DateTimeField(verbose_name='')),
                ('deleted_at', models.DateTimeField(verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='')),
                ('name', models.CharField(max_length=150, verbose_name='')),
                ('abrev', models.CharField(max_length=4, verbose_name='')),
                ('status', models.BooleanField(verbose_name='')),
                ('created_at', models.DateTimeField(verbose_name='')),
                ('updated_at', models.DateTimeField(verbose_name='')),
                ('deleted_at', models.DateTimeField(verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='identification_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, verbose_name='')),
                ('abrev', models.CharField(max_length=4, verbose_name='')),
                ('created_at', models.DateTimeField(verbose_name='')),
                ('updated_at', models.DateTimeField(verbose_name='')),
                ('deleted_at', models.DateTimeField(verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='')),
                ('name', models.CharField(max_length=150, verbose_name='')),
                ('status', models.BooleanField(verbose_name='')),
                ('created_at', models.DateTimeField(verbose_name='')),
                ('updated_at', models.DateTimeField(verbose_name='')),
                ('deleted_at', models.DateTimeField(verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='')),
                ('name', models.CharField(max_length=150, verbose_name='')),
                ('abrev', models.CharField(max_length=4, verbose_name='')),
                ('status', models.BooleanField(verbose_name='')),
                ('created_at', models.DateTimeField(verbose_name='')),
                ('updated_at', models.DateTimeField(verbose_name='')),
                ('deleted_at', models.DateTimeField(verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=200, verbose_name='')),
                ('status', models.BooleanField(verbose_name='')),
                ('created_at', models.DateTimeField(verbose_name='')),
                ('updated_at', models.DateTimeField(verbose_name='')),
                ('deleted_at', models.DateTimeField(verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='')),
                ('name', models.CharField(max_length=150, verbose_name='')),
                ('abrev', models.CharField(max_length=4, verbose_name='')),
                ('status', models.BooleanField(verbose_name='')),
                ('created_at', models.DateTimeField(verbose_name='')),
                ('updated_at', models.DateTimeField(verbose_name='')),
                ('deleted_at', models.DateTimeField(verbose_name='')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_identification_type',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='number_id',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
